---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - delivery.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.workload.metadata.name
  labels:
    app: #@ data.values.workload.metadata.name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ data.values.workload.metadata.name
  template:
    metadata:
      labels:
        app: #@ data.values.workload.metadata.name
    spec:
      containers: #@ data.values.config.spec.containers
---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.workload.metadata.name
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: #@ data.values.workload.metadata.name
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: #@ data.values.workload.metadata.name
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: #@ data.values.workload.metadata.name
            port:
              number: 80

