apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-web-app
  labels:
    app: deploy-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-web-app
  template:
    metadata:
      labels:
        app: deploy-web-app
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dmanagement.endpoint.health.probes.add-additional-paths="true" -Dmanagement.health.probes.enabled="true" -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: us-west1-docker.pkg.dev/lkimmel-1069/tap/deploy-web-app-devspace@sha256:0d3a19250d5fb8749260c45939c589be117f7870aca6babaec4128c7daa21712
        livenessProbe:
          httpGet:
            path: /livez
            port: 8080
            scheme: HTTP
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
            scheme: HTTP
        resources: {}
        securityContext:
          runAsUser: 1000

