apiVersion: v1
kind: Service
metadata:
  name: deploy-web-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: deploy-web-app
  sessionAffinity: None
  type: ClusterIP

