---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitops-repo
  namespace: tap-namespace-provisioning
spec:
  interval: 5m0s
  url: https://github.com/logankimmel/gitops
  ref:
    branch: main
