---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: desired-namespaces-cd
  namespace: default
spec:
  interval: 1m
  targetNamespace: tap-namespace-provisioning
  sourceRef:
    kind: GitRepository
    name: gitops-repo
  path: "./TAP-kustomize"
  prune: true
